name: 'citibike_dbt'
version: '1.0'
config-version: 2
profile: 'citibike_bigquery'
model-paths:
  - models
target-path: target
clean-targets:
  - target
  - dbt_modules
models:
  citibike_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
